/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador_k;

import semantico.*;
import codigoIntermedio.*;
import java.awt.Color;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

import javax.swing.JTextPane;


/**
 *
 * @author Kuzuks
 */
public class Interfaz extends javax.swing.JFrame {
public static File file;
public static int lineas;
public static int error;
public static int error_main;
public static int error_main2=0;
public static tablaSimbolos tabla = new tablaSimbolos();
public static TablaCuadruplos cuad = new TablaCuadruplos();
 
    public Interfaz() {
        initComponents();
        compilar.setEnabled(false);
        label.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filechooser = new javax.swing.JFileChooser();
        jSeparator1 = new javax.swing.JSeparator();
        examinar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        compilar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador K++");

        examinar.setText("Examinar");
        examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examinarActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        compilar.setText("Compilar");
        compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compilarActionPerformed(evt);
            }
        });

        salida.setEditable(false);
        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane2.setViewportView(salida);

        jLabel1.setText("Output:");

        jLabel2.setText("Code:");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        label.setText("Guardado con exito!");

        help.setText("Help");
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
        });
        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(compilar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(examinar))
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(examinar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compilar)
                    .addComponent(jButton1)
                    .addComponent(saveBtn)
                    .addComponent(label))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void examinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examinarActionPerformed
        // TODO add your handling code here:
        salida.setText("");
        label.setVisible(false);
        int returnVal = filechooser.showOpenDialog(this);
    if (returnVal == filechooser.APPROVE_OPTION) {
         file = filechooser.getSelectedFile();
        try {
          textArea.read( new FileReader( file.getAbsolutePath() ), null );
          textArea.setEditable(true);
          compilar.setEnabled(true);
         
          LineNumber = new TextLineNumber(textArea, 3);
          LineNumber.setUpdateFont(true);
          jScrollPane1.setRowHeaderView(LineNumber);
          
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
           
    } else {
        System.out.println("File access cancelled by user.");
    }
    
    }//GEN-LAST:event_examinarActionPerformed

    private void compilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compilarActionPerformed
        salida.setText("");
        salida.setForeground(Color.black);
        error_main=0;
        label.setVisible(false);
        try {
            Lexer Scan = new Lexer(new FileInputStream(file.getAbsolutePath()));
            Analizador p = new Analizador(Scan);
            Object result = p.parse().value;  
            label.setVisible(false);
            LineNumber2 = new TextLineNumber(salida, 3);
            LineNumber2.setUpdateFont(true);
            jScrollPane2.setRowHeaderView(LineNumber2);
            if(error_main ==0){
                salida.setText(salida.getText()+"No se encontro Main(),Se requiere que el programa tenga un Main\n");
                error=1;
            }
            if (error_main>1){
                salida.setText(salida.getText()+"No puede estar declarado mas de un Main()\n");
            }
            if(error==1){
                salida.setForeground(Color.red);
            }
            if (error==0 && error_main ==1){
                 salida.setForeground(Color.GREEN);
                 salida.setText(salida.getText()+"Compilacion fue exitosa!\n");
                  System.out.println(tabla.getLineasTabla().toString());
                  Lexer Scan2 = new Lexer(new FileInputStream(file.getAbsolutePath()));
                  intermedio i = new intermedio(Scan2);
                  Object result1 = i.parse().value;
                 System.out.println("\nfin");
                 //System.out.print(tabla.getLineasTabla());
                   ArrayList<lineaTabla> lines = tabla.getLineasTabla();
                   ArrayList<Cuadruplo> linescuad = cuad.tabla_cuad;
                 //String tablaSim = tabla.getLineasTabla().toString()+"\n";
                 File file = new File("src/outputs/TablaSimbolos.txt");
                 if (!file.exists()) {
				file.createNewFile();
                  } 
                 
                 //File file2 = new File("C:/Users/Kuzuks/Desktop/tablaCuad.txt");
                 //if (!file2.exists()) {
		//		file2.createNewFile();
                 // }        
                 
                  PrintWriter pw = new PrintWriter(new FileOutputStream(file));
                  for(lineaTabla linea :lines){
                      pw.println(linea.toString());
                  }
                  pw.close();
                  
                  // PrintWriter pw2 = new PrintWriter(new FileOutputStream(file2));
                  //for(Cuadruplo lineacuad :linescuad){
                 //     pw2.println(lineacuad.toString());
                 // }
                 // pw2.close();
                   cuad.PrintTabla();
                   CodigoFinal Final = new CodigoFinal(i.getCuadruplos(),p.tablaSim,i.getLiterals());
                   Final.generarFinal();
                   Final.escribir();
                   
            }
            
            
          } catch (Exception e) {
          }
            
    }//GEN-LAST:event_compilarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    salida.setText("");
    lineas=0; 
    label.setVisible(false);
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    try {
        BufferedWriter outFile = new BufferedWriter(new FileWriter(file));
               outFile.write(textArea.getText()); //put in textfile
               error=0;
              label.setVisible(true);
              salida.setText("");
               outFile.close();
    } catch (IOException ex) {
        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
        JFrame framcito = new JFrame("Ayuda");
        JTextPane pane = new JTextPane();
        framcito.setSize(420,460);
        framcito.setLocation(510, 40);
        framcito.show(true);
        framcito.setResizable(false);
        BufferedReader in = null;
        pane.setText(ayuda.ayuda);
        framcito.add(pane);
        pane.setEditable(false);
     
           
    }//GEN-LAST:event_helpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Interfaz().setVisible(true);
            }
        });
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compilar;
    private javax.swing.JButton examinar;
    private javax.swing.JFileChooser filechooser;
    private javax.swing.JMenu help;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label;
    public static javax.swing.JTextArea salida;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    private TextLineNumber LineNumber;
    private TextLineNumber LineNumber2;


}
