/* The following code was generated by JFlex 1.4.3 on 09-17-13 07:48 PM */

package compilador_k;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 09-17-13 07:48 PM from the specification file
 * <tt>src/compilador_k/LexerPresentacion.flex</tt>
 */
class LexerPresentacion {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 4;
  public static final int COMMENTML = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\22\1\23\2\0\1\23\22\0\1\21\1\44\1\52\4\0"+
    "\1\51\1\31\1\32\1\37\1\36\1\27\1\35\1\26\1\40\1\2"+
    "\11\50\1\25\1\24\1\41\1\43\1\42\2\0\5\1\1\57\15\1"+
    "\1\60\6\1\1\0\1\53\2\0\1\30\1\0\1\13\1\54\1\11"+
    "\1\6\1\45\1\15\1\20\1\12\1\5\2\1\1\16\1\55\1\7"+
    "\1\4\1\47\1\1\1\14\1\17\1\10\1\56\1\3\1\46\3\1"+
    "\1\33\1\0\1\34\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\6\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\1\3\2"+
    "\1\3\2\1\3\2\1\4\1\25\3\0\2\2\1\26"+
    "\7\2\1\27\1\30\1\31\1\32\1\33\1\34\5\2"+
    "\2\0\1\35\1\0\3\2\1\36\13\2\1\37\5\2"+
    "\1\0\4\2\1\0\1\26\1\2\2\0\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\u01b9\0\u01ea\0\u021b\0\223\0\223\0\223\0\223"+
    "\0\223\0\223\0\223\0\223\0\223\0\223\0\223\0\223"+
    "\0\223\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372"+
    "\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa"+
    "\0\223\0\u052b\0\365\0\u055c\0\u058d\0\u05be\0\304\0\u05ef"+
    "\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715\0\223\0\223"+
    "\0\223\0\223\0\223\0\223\0\u0746\0\u0777\0\u07a8\0\u07d9"+
    "\0\u080a\0\u083b\0\u0436\0\223\0\u086c\0\u089d\0\u08ce\0\u08ff"+
    "\0\u055c\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56"+
    "\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\223\0\u0b4b\0\u0b7c\0\u0bad"+
    "\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35"+
    "\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\223";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\5\1\10\3\5\1\11"+
    "\2\5\1\12\1\13\1\5\1\14\1\5\3\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\4\1\5"+
    "\1\45\1\5\1\46\1\47\37\15\1\50\44\15\1\51"+
    "\35\15\62\0\20\5\7\0\1\52\14\0\4\5\3\0"+
    "\5\5\2\0\1\53\23\0\1\54\21\0\1\53\11\0"+
    "\3\5\1\55\14\5\7\0\1\52\14\0\4\5\3\0"+
    "\5\5\1\0\6\5\1\56\5\5\1\57\3\5\7\0"+
    "\1\52\14\0\4\5\3\0\5\5\1\0\11\5\1\60"+
    "\6\5\7\0\1\52\14\0\4\5\3\0\5\5\1\0"+
    "\20\5\7\0\1\52\14\0\1\61\3\5\3\0\5\5"+
    "\1\0\3\5\1\62\11\5\1\63\2\5\7\0\1\52"+
    "\14\0\4\5\3\0\2\5\1\64\2\5\1\0\7\5"+
    "\1\65\1\66\7\5\7\0\1\52\14\0\4\5\3\0"+
    "\5\5\37\0\1\67\1\70\63\0\1\71\60\0\1\72"+
    "\60\0\1\73\60\0\1\74\16\0\6\5\1\75\6\5"+
    "\1\76\2\5\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\1\0\11\5\1\77\1\5\1\100\4\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\1\0\13\5\1\101\4\5"+
    "\7\0\1\52\14\0\4\5\3\0\5\5\2\0\1\42"+
    "\23\0\1\54\21\0\1\42\10\0\23\102\1\0\35\102"+
    "\23\103\1\0\26\103\1\104\1\105\5\103\1\0\12\5"+
    "\1\106\5\5\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\1\0\12\5\1\107\5\5\7\0\1\52\14\0\4\5"+
    "\3\0\5\5\1\0\13\5\1\110\4\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\40\0\1\51\21\0\20\5"+
    "\24\0\4\5\3\0\5\5\2\0\1\111\45\0\1\111"+
    "\11\0\4\5\1\112\13\5\7\0\1\52\14\0\4\5"+
    "\3\0\5\5\1\0\7\5\1\57\10\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\1\0\12\5\1\62\5\5"+
    "\7\0\1\52\14\0\4\5\3\0\5\5\1\0\7\5"+
    "\1\113\10\5\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\1\0\13\5\1\57\4\5\7\0\1\52\14\0\4\5"+
    "\3\0\5\5\1\0\3\5\1\114\14\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\1\0\6\5\1\115\11\5"+
    "\7\0\1\52\14\0\4\5\3\0\5\5\1\0\13\5"+
    "\1\116\4\5\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\1\0\12\5\1\117\5\5\7\0\1\52\14\0\4\5"+
    "\3\0\5\5\1\0\5\5\1\120\12\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\1\0\16\5\1\121\1\5"+
    "\7\0\1\52\14\0\4\5\3\0\5\5\1\0\4\5"+
    "\1\122\13\5\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\1\0\4\5\1\123\13\5\7\0\1\52\14\0\4\5"+
    "\3\0\5\5\1\0\4\5\1\124\13\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\51\0\1\125\16\0\2\103"+
    "\3\0\2\103\33\0\4\103\5\0\4\5\1\126\13\5"+
    "\7\0\1\52\14\0\4\5\3\0\5\5\1\0\15\5"+
    "\1\76\2\5\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\1\0\20\5\7\0\1\52\14\0\4\5\3\0\2\5"+
    "\1\121\2\5\1\0\5\5\1\57\12\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\1\0\20\5\7\0\1\52"+
    "\14\0\4\5\3\0\2\5\1\127\2\5\1\0\12\5"+
    "\1\56\5\5\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\1\0\10\5\1\130\7\5\7\0\1\52\14\0\4\5"+
    "\3\0\5\5\1\0\4\5\1\131\13\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\1\0\6\5\1\132\11\5"+
    "\7\0\1\52\14\0\4\5\3\0\5\5\1\0\20\5"+
    "\1\133\6\0\1\52\14\0\4\5\3\0\5\5\1\0"+
    "\20\5\7\0\1\52\14\0\1\57\3\5\3\0\5\5"+
    "\1\0\15\5\1\121\2\5\7\0\1\52\14\0\4\5"+
    "\3\0\5\5\1\0\7\5\1\134\10\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\1\0\6\5\1\135\11\5"+
    "\7\0\1\52\14\0\4\5\3\0\5\5\1\0\6\5"+
    "\1\57\11\5\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\1\0\13\5\1\126\4\5\7\0\1\52\14\0\4\5"+
    "\3\0\5\5\1\0\7\5\1\136\10\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\1\0\6\5\1\137\11\5"+
    "\7\0\1\52\14\0\4\5\3\0\5\5\1\0\14\5"+
    "\1\57\3\5\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\55\0\1\140\4\0\20\5\7\0\1\52\14\0\1\141"+
    "\3\5\3\0\5\5\1\0\7\5\1\132\10\5\7\0"+
    "\1\52\14\0\4\5\3\0\5\5\1\0\4\5\1\142"+
    "\13\5\7\0\1\52\14\0\4\5\3\0\5\5\1\0"+
    "\17\5\1\57\7\0\1\52\14\0\4\5\3\0\5\5"+
    "\13\0\1\143\46\0\15\5\1\126\2\5\7\0\1\52"+
    "\14\0\4\5\3\0\5\5\1\0\3\5\1\126\14\5"+
    "\7\0\1\52\14\0\4\5\3\0\5\5\5\0\1\144"+
    "\62\0\1\145\51\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3626];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\10\1\15\11\17\1\1\11\3\0\12\1"+
    "\6\11\5\1\2\0\1\11\1\0\17\1\1\11\5\1"+
    "\1\0\4\1\1\0\2\1\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerPresentacion(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerPresentacion(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { System.out.println("Tok par_left: "+ yytext() + " reconocido");
          }
        case 32: break;
        case 18: 
          { System.out.println("Tok less: "+ yytext() + " reconocido");
          }
        case 33: break;
        case 24: 
          { yybegin (COMMENT);
          }
        case 34: break;
        case 28: 
          { System.out.println("Tok diff: "+ yytext() + " reconocido");
          }
        case 35: break;
        case 7: 
          { System.out.println("Tok dot: "+ yytext() + " reconocido");
          }
        case 36: break;
        case 21: 
          { yybegin(YYINITIAL);
          }
        case 37: break;
        case 26: 
          { System.out.println("Tok greater_equal: "+ yytext() + " reconocido");
          }
        case 38: break;
        case 15: 
          { System.out.println("Tok plus: "+ yytext() + " reconocido");
          }
        case 39: break;
        case 8: 
          { System.out.println("Tok comma: "+ yytext() + " reconocido");
          }
        case 40: break;
        case 14: 
          { System.out.println("Tok minus: "+ yytext() + " reconocido");
          }
        case 41: break;
        case 16: 
          { System.out.println("Tok mult: "+ yytext() + " reconocido");
          }
        case 42: break;
        case 13: 
          { System.out.println("Tok brack_right: "+ yytext() + " reconocido");
          }
        case 43: break;
        case 11: 
          { System.out.println("Tok par_right: "+ yytext() + " reconocido");
          }
        case 44: break;
        case 17: 
          { System.out.println("Tok div: "+ yytext() + " reconocido");
          }
        case 45: break;
        case 29: 
          { System.out.println("Tok string_literal: "+ yytext() + " reconocido");
          }
        case 46: break;
        case 23: 
          { yybegin (COMMENTML);
          }
        case 47: break;
        case 3: 
          { System.out.println("Tok int_literal: "+ yytext() + " reconocido");
          }
        case 48: break;
        case 31: 
          { System.out.println("Tok char_literal: "+ yytext() + " reconocido");
          }
        case 49: break;
        case 22: 
          { System.out.println("Tok "+ yytext() + " reconocido");
          }
        case 50: break;
        case 6: 
          { System.out.println("Tok colon: "+ yytext() + " reconocido");
          }
        case 51: break;
        case 27: 
          { System.out.println("Tok equal_comp: "+ yytext() + " reconocido");
          }
        case 52: break;
        case 19: 
          { System.out.println("Tok greater: "+ yytext() + " reconocido");
          }
        case 53: break;
        case 9: 
          { System.out.println("Tok underline: "+ yytext() + " reconocido");
          }
        case 54: break;
        case 1: 
          { System.out.println("Tok " + yytext()+ " no reconocido en la linea: "+ yyline+1 + " columna: "+ yycolumn+1);
          }
        case 55: break;
        case 5: 
          { System.out.println("Tok semicolon: "+ yytext() + " reconocido");
          }
        case 56: break;
        case 25: 
          { System.out.println("Tok less_equal: "+ yytext() + " reconocido");
          }
        case 57: break;
        case 20: 
          { System.out.println("Tok equal_asig: "+ yytext() + " reconocido");
          }
        case 58: break;
        case 12: 
          { System.out.println("Tok brack_left: "+ yytext() + " reconocido");
          }
        case 59: break;
        case 30: 
          { System.out.println("Tok float_literal: "+ yytext() + " reconocido");
          }
        case 60: break;
        case 2: 
          { System.out.println("Tok id: "+ yytext() + " reconocido");
          }
        case 61: break;
        case 4: 
          { 
          }
        case 62: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
