
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 15 22:06:18 CST 2013
//----------------------------------------------------

package codigoIntermedio;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 12;
  public static final int SCANF = 31;
  public static final int BRACK_LEFT = 18;
  public static final int MULT = 8;
  public static final int CHAR = 24;
  public static final int CHAR_LITERAL = 4;
  public static final int PAR_LEFT = 16;
  public static final int INT = 21;
  public static final int FOR = 27;
  public static final int MINUS = 6;
  public static final int SEMICOLON = 14;
  public static final int AND = 33;
  public static final int ELSEIF = 29;
  public static final int PAR_RIGHT = 17;
  public static final int OR = 32;
  public static final int COMMA = 15;
  public static final int DIV = 9;
  public static final int ASSIGNATIONS = 11;
  public static final int PLUS = 7;
  public static final int MAIN = 35;
  public static final int IF = 25;
  public static final int AMPERSAND = 34;
  public static final int ID = 5;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int error = 1;
  public static final int OPERADORES = 10;
  public static final int VOID = 13;
  public static final int PRINTF = 30;
  public static final int ELSE = 26;
  public static final int WHILE = 28;
  public static final int FLOAT = 23;
  public static final int STRING = 22;
  public static final int FLOAT_LITERAL = 3;
  public static final int BRACK_RIGHT = 19;
  public static final int INT_LITERAL = 2;
  public static final int INCREMENTADORES = 20;
}

